"use client";

import { useMemo, useState } from "react";
import { Button, EmptyState, Field, Modal, PageHeader, StatusBadge } from "@/components/ui";
import { Icon } from "@/components/icons";
import { useWorkspace } from "@/context/workspace-context";
import type { Priority, Project, ProjectStatus } from "@/types";

const statuses: ProjectStatus[] = ["PLANNING", "IN_PROGRESS", "TESTING", "PAUSED", "COMPLETED"];
const priorities: Priority[] = ["LOW", "MEDIUM", "HIGH"];
const blank = { name: "", description: "", status: "PLANNING" as ProjectStatus, priority: "MEDIUM" as Priority, members: [] as string[], sourceIdeaId: undefined as string | undefined };

export default function ProjectsPage() {
  const { projects, team, tasks, ideas, saveProject, deleteProject } = useWorkspace();
  const [query, setQuery] = useState(""); const [filter, setFilter] = useState("ALL");
  const [open, setOpen] = useState(false); const [editing, setEditing] = useState<Project | null>(null); const [detail, setDetail] = useState<Project | null>(null); const [form, setForm] = useState(blank);
  const visible = useMemo(() => projects.filter((project) => (filter === "ALL" || project.status === filter) && `${project.name} ${project.description}`.toLowerCase().includes(query.toLowerCase())), [projects, filter, query]);
  const showForm = (project?: Project) => { setEditing(project ?? null); setForm(project ? { name: project.name, description: project.description, status: project.status, priority: project.priority, members: project.members, sourceIdeaId: project.sourceIdeaId } : blank); setOpen(true); };
  const submit = async (event: React.FormEvent) => { event.preventDefault(); await saveProject(form, editing?.id); setOpen(false); };
  const remove = async (project: Project) => { if (window.confirm(`¿Eliminar “${project.name}” y todas sus tareas?`)) { await deleteProject(project.id); setDetail(null); } };
  const toggleMember = (id: string) => setForm({...form, members: form.members.includes(id) ? form.members.filter((member) => member !== id) : [...form.members,id]});

  return <>
    <PageHeader eyebrow="Construir con intención" title="Proyectos" description="Convierte las oportunidades seleccionadas en trabajo enfocado y visible." action={<Button icon="plus" onClick={() => showForm()}>Nuevo proyecto</Button>} />
    <div className="toolbar"><div className="search-box"><Icon name="search" width={17}/><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Buscar proyectos…" aria-label="Buscar proyectos"/></div><select className="filter-select" value={filter} onChange={(e) => setFilter(e.target.value)} aria-label="Filtrar proyectos"><option value="ALL">Todos los estados</option>{statuses.map((status) => <option key={status} value={status}>{status.replaceAll("_"," ")}</option>)}</select></div>
    {visible.length ? <section className="card-grid">{visible.map((project) => <article className="panel project-card" key={project.id} onClick={() => setDetail(project)}><div className="project-card-top"><span className="project-symbol"><Icon name="projects" width={17}/></span><StatusBadge value={project.status}/></div><h3>{project.name}</h3><p>{project.description}</p><div className="project-card-foot"><div className="member-stack">{project.members.slice(0,4).map((id) => { const member = team.find((item) => item.id === id); return <span className="member-mini" key={id} title={member?.name}>{member?.name.slice(0,2).toUpperCase() ?? "?"}</span>; })}</div><StatusBadge value={project.priority}/></div></article>)}</section> : <section className="panel"><EmptyState title="No hay proyectos que mostrar" text="Crea un proyecto o ajusta los filtros."/></section>}
    {detail && <><button className="drawer-scrim" onClick={() => setDetail(null)} aria-label="Cerrar detalle"/><aside className="detail-drawer"><div className="detail-top"><div><StatusBadge value={detail.status}/><h2>{detail.name}</h2></div><button className="icon-button" onClick={() => setDetail(null)} aria-label="Cerrar"><Icon name="close" width={20}/></button></div><p className="detail-description">{detail.description}</p><div className="detail-section"><h3>Resumen</h3><div className="detail-facts"><span><small>Prioridad</small><StatusBadge value={detail.priority}/></span><span><small>Responsable</small>{detail.ownerName}</span><span><small>Miembros</small>{detail.members.length}</span><span><small>Tareas</small>{tasks.filter((task) => task.projectId === detail.id).length}</span>{detail.sourceIdeaId && <span><small>Idea de origen</small>{ideas.find((idea) => idea.id === detail.sourceIdeaId)?.title ?? detail.sourceIdeaId}</span>}</div></div><div className="detail-section"><h3>Equipo</h3><div className="member-stack">{detail.members.map((id) => { const member=team.find((item)=>item.id===id); return <span className="member-mini" key={id} title={member?.name}>{member?.name.slice(0,2).toUpperCase() ?? "?"}</span>; })}</div></div><div className="detail-actions"><Button variant="secondary" onClick={() => { setDetail(null); showForm(detail); }}>Editar proyecto</Button><Button variant="danger" onClick={() => remove(detail)}>Eliminar proyecto</Button></div></aside></>}
    <Modal open={open} onClose={() => setOpen(false)} title={editing ? "Editar proyecto" : "Nuevo proyecto"} subtitle="Define el objetivo y reúne al equipo adecuado."><form className="form-grid" onSubmit={submit}><Field label="Nombre"><input required maxLength={100} value={form.name} onChange={(e)=>setForm({...form,name:e.target.value})} autoFocus/></Field><Field label="Estado"><select value={form.status} onChange={(e)=>setForm({...form,status:e.target.value as ProjectStatus})}>{statuses.map((status)=><option key={status} value={status}>{status.replaceAll("_"," ")}</option>)}</select></Field><div className="field-wide"><Field label="Descripción"><textarea required maxLength={700} value={form.description} onChange={(e)=>setForm({...form,description:e.target.value})}/></Field></div><Field label="Prioridad"><select value={form.priority} onChange={(e)=>setForm({...form,priority:e.target.value as Priority})}>{priorities.map((priority)=><option key={priority} value={priority}>{priority}</option>)}</select></Field><Field label="Idea de origen (opcional)"><select value={form.sourceIdeaId ?? ""} onChange={(e)=>setForm({...form,sourceIdeaId:e.target.value || undefined})}><option value="">Sin idea vinculada</option>{ideas.map((idea)=><option key={idea.id} value={idea.id}>{idea.title}</option>)}</select></Field><div className="field-wide"><Field label="Miembros"><div className="checkbox-grid">{team.map((member)=><label key={member.id} className="check-option"><input type="checkbox" checked={form.members.includes(member.id)} onChange={()=>toggleMember(member.id)}/><span>{member.name}</span></label>)}</div></Field></div><div className="modal-actions"><Button type="button" variant="secondary" onClick={()=>setOpen(false)}>Cancelar</Button><Button type="submit">{editing ? "Guardar cambios" : "Crear proyecto"}</Button></div></form></Modal>
  </>;
}
